# application-prod.yml (AWS)

spring:
# MySQL
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/anime?serverTimezone=UTC&serverTimezone=GMT%2b8&characterEncoding=utf8
      username: root
      password: fubuki0728anime
  jackson:
    time-zone: GMT+8